apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    app: my-httpd
spec:
  restartPolicy: Always
  imagePullSecrets:
    - name: my-ecr-creds
  containers:
    - name: httpd-container
      image: 984303072552.dkr.ecr.us-east-1.amazonaws.com/my-httpd:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 80